export const FEELING_CHIPS = [
  'neutral',
  'leer',
  'erschöpft',
  'angespannt',
  'überwältigt',
  'gereizt',
  'abgestumpft',
  'traurig',
  'ängstlich',
  'leicht',
  'frustriert',
  'zufrieden',
  'freudig',
  'dankbar',
  'motiviert',
  'verwirrt',
  'aufgedreht',
] as const;

export const SELF_CARE_CHIPS = [
  'Augen schließen',
  'Licht dimmen',
  'Nichts entscheiden',
  'Einfach bleiben',
  'Wasser trinken',
  'Kurz raus',
  'Tief atmen',
  'Dehnen',
  'Spazieren',
  'Essen',
  'Dusche',
  'Musik hören',
] as const;
